# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buy_plan.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Buy_Plan_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 519)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.drug_name_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.drug_name_label.setFont(font)
        self.drug_name_label.setAlignment(QtCore.Qt.AlignCenter)
        self.drug_name_label.setObjectName("drug_name_label")
        self.price_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.price_label.setFont(font)
        self.price_label.setAlignment(QtCore.Qt.AlignCenter)
        self.price_label.setObjectName("price_label")
        self.number_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.number_label.setFont(font)
        self.number_label.setAlignment(QtCore.Qt.AlignCenter)
        self.number_label.setObjectName("number_label")
        self.total_label = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.total_label.setFont(font)
        self.total_label.setAlignment(QtCore.Qt.AlignCenter)
        self.total_label.setObjectName("total_label")
        self.verticalLayout.addWidget(self.splitter)
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.drug_name_input_1 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.drug_name_input_1.setFont(font)
        self.drug_name_input_1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.drug_name_input_1.setText("")
        self.drug_name_input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.drug_name_input_1.setObjectName("drug_name_input_1")
        self.price_input_1 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.price_input_1.setFont(font)
        self.price_input_1.setText("")
        self.price_input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.price_input_1.setObjectName("price_input_1")
        self.number_input_1 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.number_input_1.setFont(font)
        self.number_input_1.setMouseTracking(False)
        self.number_input_1.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.number_input_1.setText("")
        self.number_input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.number_input_1.setObjectName("number_input_1")
        self.total_input_1 = QtWidgets.QLineEdit(self.splitter_2)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.total_input_1.setFont(font)
        self.total_input_1.setText("")
        self.total_input_1.setAlignment(QtCore.Qt.AlignCenter)
        self.total_input_1.setObjectName("total_input_1")
        self.verticalLayout.addWidget(self.splitter_2)
        self.splitter_3 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.drug_name_input_2 = QtWidgets.QLineEdit(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.drug_name_input_2.setFont(font)
        self.drug_name_input_2.setText("")
        self.drug_name_input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.drug_name_input_2.setObjectName("drug_name_input_2")
        self.price_input_2 = QtWidgets.QLineEdit(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.price_input_2.setFont(font)
        self.price_input_2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.price_input_2.setText("")
        self.price_input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.price_input_2.setObjectName("price_input_2")
        self.number_input_2 = QtWidgets.QLineEdit(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.number_input_2.setFont(font)
        self.number_input_2.setMouseTracking(False)
        self.number_input_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.number_input_2.setText("")
        self.number_input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.number_input_2.setObjectName("number_input_2")
        self.total_input_2 = QtWidgets.QLineEdit(self.splitter_3)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.total_input_2.setFont(font)
        self.total_input_2.setText("")
        self.total_input_2.setAlignment(QtCore.Qt.AlignCenter)
        self.total_input_2.setObjectName("total_input_2")
        self.verticalLayout.addWidget(self.splitter_3)
        self.splitter_4 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.drug_name_input_3 = QtWidgets.QLineEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.drug_name_input_3.setFont(font)
        self.drug_name_input_3.setText("")
        self.drug_name_input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.drug_name_input_3.setObjectName("drug_name_input_3")
        self.price_input_3 = QtWidgets.QLineEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.price_input_3.setFont(font)
        self.price_input_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.price_input_3.setText("")
        self.price_input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.price_input_3.setObjectName("price_input_3")
        self.number_input_3 = QtWidgets.QLineEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.number_input_3.setFont(font)
        self.number_input_3.setMouseTracking(False)
        self.number_input_3.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.number_input_3.setText("")
        self.number_input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.number_input_3.setObjectName("number_input_3")
        self.total_input_3 = QtWidgets.QLineEdit(self.splitter_4)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.total_input_3.setFont(font)
        self.total_input_3.setText("")
        self.total_input_3.setAlignment(QtCore.Qt.AlignCenter)
        self.total_input_3.setObjectName("total_input_3")
        self.verticalLayout.addWidget(self.splitter_4)
        self.splitter_5 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_5.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_5.setObjectName("splitter_5")
        self.drug_name_input_4 = QtWidgets.QLineEdit(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.drug_name_input_4.setFont(font)
        self.drug_name_input_4.setText("")
        self.drug_name_input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.drug_name_input_4.setObjectName("drug_name_input_4")
        self.price_input_4 = QtWidgets.QLineEdit(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.price_input_4.setFont(font)
        self.price_input_4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.price_input_4.setText("")
        self.price_input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.price_input_4.setObjectName("price_input_4")
        self.number_input_4 = QtWidgets.QLineEdit(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.number_input_4.setFont(font)
        self.number_input_4.setMouseTracking(False)
        self.number_input_4.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.number_input_4.setText("")
        self.number_input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.number_input_4.setObjectName("number_input_4")
        self.total_input_4 = QtWidgets.QLineEdit(self.splitter_5)
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(18)
        self.total_input_4.setFont(font)
        self.total_input_4.setText("")
        self.total_input_4.setAlignment(QtCore.Qt.AlignCenter)
        self.total_input_4.setObjectName("total_input_4")
        self.verticalLayout.addWidget(self.splitter_5)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check_btn = QtWidgets.QPushButton(self.centralwidget)
        self.check_btn.setObjectName("check_btn")
        self.horizontalLayout.addWidget(self.check_btn)
        self.cancel_btn = QtWidgets.QPushButton(self.centralwidget)
        self.cancel_btn.setObjectName("cancel_btn")
        self.horizontalLayout.addWidget(self.cancel_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 829, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.drug_name_label.setText(_translate("MainWindow", "药 品 名"))
        self.price_label.setText(_translate("MainWindow", "单       价"))
        self.number_label.setText(_translate("MainWindow", "数      量"))
        self.total_label.setText(_translate("MainWindow", "总       价"))
        self.check_btn.setText(_translate("MainWindow", "确定"))
        self.cancel_btn.setText(_translate("MainWindow", "取消"))
