# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sign_up.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow


class Sign_up_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.sign_up_label = QtWidgets.QLabel(self.centralwidget)
        self.sign_up_label.setGeometry(QtCore.QRect(210, 10, 379, 132))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(72)
        self.sign_up_label.setFont(font)
        self.sign_up_label.setAlignment(QtCore.Qt.AlignCenter)
        self.sign_up_label.setObjectName("sign_up_label")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(250, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.username_label.setFont(font)
        self.username_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.username_label.setObjectName("username_label")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(380, 170, 201, 31))
        self.username_input.setObjectName("username_input")
        self.pwd_label = QtWidgets.QLabel(self.centralwidget)
        self.pwd_label.setGeometry(QtCore.QRect(250, 210, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.pwd_label.setFont(font)
        self.pwd_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pwd_label.setObjectName("pwd_label")
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setGeometry(QtCore.QRect(250, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.name_label.setFont(font)
        self.name_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.name_label.setObjectName("name_label")
        self.phone_label = QtWidgets.QLabel(self.centralwidget)
        self.phone_label.setGeometry(QtCore.QRect(250, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.phone_label.setFont(font)
        self.phone_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.phone_label.setObjectName("phone_label")
        self.sex_label = QtWidgets.QLabel(self.centralwidget)
        self.sex_label.setGeometry(QtCore.QRect(250, 330, 121, 31))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(18)
        self.sex_label.setFont(font)
        self.sex_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.sex_label.setObjectName("sex_label")
        self.pwd_input = QtWidgets.QLineEdit(self.centralwidget)
        self.pwd_input.setGeometry(QtCore.QRect(380, 210, 201, 31))
        self.pwd_input.setObjectName("pwd_input")
        self.name_input = QtWidgets.QLineEdit(self.centralwidget)
        self.name_input.setGeometry(QtCore.QRect(380, 250, 201, 31))
        self.name_input.setObjectName("name_input")
        self.phone_input = QtWidgets.QLineEdit(self.centralwidget)
        self.phone_input.setGeometry(QtCore.QRect(380, 290, 201, 31))
        self.phone_input.setObjectName("phone_input")
        self.sex_input = QtWidgets.QLineEdit(self.centralwidget)
        self.sex_input.setGeometry(QtCore.QRect(380, 330, 201, 31))
        self.sex_input.setObjectName("sex_input")
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ok_btn.setGeometry(QtCore.QRect(320, 410, 121, 51))
        self.ok_btn.setObjectName("ok_btn")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sign_up_label.setText(_translate("MainWindow", "注册"))
        self.username_label.setText(_translate("MainWindow", "用户名："))
        self.pwd_label.setText(_translate("MainWindow", "密码："))
        self.name_label.setText(_translate("MainWindow", "真实姓名："))
        self.phone_label.setText(_translate("MainWindow", "电话："))
        self.sex_label.setText(_translate("MainWindow", "性别："))
        self.ok_btn.setText(_translate("MainWindow", "确定"))

if __name__ == '__main__':
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    ui = Sign_up_MainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())
